#pragma once

#define PALM_PROFILE_IIIX 1
#define PALM_PROFILE_M100_EXPERIMENTAL 2

#ifndef PALM_HARDWARE_PROFILE
#define PALM_HARDWARE_PROFILE PALM_PROFILE_IIIX
#endif

#if PALM_HARDWARE_PROFILE == PALM_PROFILE_IIIX
#define PALM_PROFILE_NAME "Palm IIIx"
#define PALM_RAM_BASE 0x00000000UL
#define PALM_RAM_LOGICAL_SIZE (4UL * 1024UL * 1024UL)
#define PALM_RAM_TOP_ALIAS_END 0x01000000UL
#define PALM_ROM_BASE 0x10c08000UL
#define PALM_ROM_LOW_ALIAS_BASE 0x10c00000UL
#define PALM_ROM_CHIP_SELECT_SIZE (16UL * 1024UL * 1024UL)
#define PALM_ENABLE_24BIT_ALIASES 1
#define PALM_LCD_W 160
#define PALM_LCD_H 160
#define PALM_SILKSCREEN_H 60

#elif PALM_HARDWARE_PROFILE == PALM_PROFILE_M100_EXPERIMENTAL
// Compile-time skeleton only. Hardware identity and peripheral behavior still
// need validation against an m100 ROM before this should be treated as working.
#define PALM_PROFILE_NAME "Palm m100 experimental"
#define PALM_RAM_BASE 0x00000000UL
#define PALM_RAM_LOGICAL_SIZE (2UL * 1024UL * 1024UL)
#define PALM_RAM_TOP_ALIAS_END 0x01000000UL
#define PALM_ROM_BASE 0x10c08000UL
#define PALM_ROM_LOW_ALIAS_BASE 0x10c00000UL
#define PALM_ROM_CHIP_SELECT_SIZE (16UL * 1024UL * 1024UL)
#define PALM_ENABLE_24BIT_ALIASES 1
#define PALM_LCD_W 160
#define PALM_LCD_H 160
#define PALM_SILKSCREEN_H 60

#else
#error Unsupported PALM_HARDWARE_PROFILE
#endif

#define PALM_ROM_LOW_24BIT_ALIAS_BASE (PALM_ROM_LOW_ALIAS_BASE & 0x00ffffffUL)
#define PALM_ROM_24BIT_BASE (PALM_ROM_BASE & 0x00ffffffUL)
#define PALM_DIGITIZER_W PALM_LCD_W
#define PALM_DIGITIZER_H (PALM_LCD_H + PALM_SILKSCREEN_H)
#define PALM_LCD_BYTES ((PALM_LCD_W * PALM_LCD_H) / 8)
