<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PalmRamProbe</RootNamespace>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\NativeMusashi\build-release\PalmMusashi.dll" Link="PalmMusashi.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\NativeMusashi\build-release\PalmMusashi.dll')" />
  </ItemGroup>
</Project>
